# Change baseurl before deploy
baseurl = "https://a-moment096.github.io/"
languageCode = "zh"
title = "A Moment's Rest"
theme = "stack"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh, zh-hant-tw, zh-hant-hk, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

timeZone = "Etc/GMT-8"

[pagination]
pagerSize = 20

[frontmatter]
lastmod=["lastmod",":fileModTime"]